# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/stuart/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/stuart/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stuart/Code/mlx90640-library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stuart/Code/mlx90640-library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/stuart/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/stuart/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/182.3911.40/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stuart/Code/mlx90640-library/CMakeFiles /home/stuart/Code/mlx90640-library/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stuart/Code/mlx90640-library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mlx90640_library

# Build rule for target.
mlx90640_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mlx90640_library
.PHONY : mlx90640_library

# fast build rule for target.
mlx90640_library/fast:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/build
.PHONY : mlx90640_library/fast

examples/fb.o: examples/fb.c.o

.PHONY : examples/fb.o

# target to build an object file
examples/fb.c.o:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/examples/fb.c.o
.PHONY : examples/fb.c.o

examples/fb.i: examples/fb.c.i

.PHONY : examples/fb.i

# target to preprocess a source file
examples/fb.c.i:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/examples/fb.c.i
.PHONY : examples/fb.c.i

examples/fb.s: examples/fb.c.s

.PHONY : examples/fb.s

# target to generate assembly for a file
examples/fb.c.s:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/examples/fb.c.s
.PHONY : examples/fb.c.s

examples/fbuf.o: examples/fbuf.cpp.o

.PHONY : examples/fbuf.o

# target to build an object file
examples/fbuf.cpp.o:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/examples/fbuf.cpp.o
.PHONY : examples/fbuf.cpp.o

examples/fbuf.i: examples/fbuf.cpp.i

.PHONY : examples/fbuf.i

# target to preprocess a source file
examples/fbuf.cpp.i:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/examples/fbuf.cpp.i
.PHONY : examples/fbuf.cpp.i

examples/fbuf.s: examples/fbuf.cpp.s

.PHONY : examples/fbuf.s

# target to generate assembly for a file
examples/fbuf.cpp.s:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/examples/fbuf.cpp.s
.PHONY : examples/fbuf.cpp.s

mlx90640/MLX90640_API_stub.o: mlx90640/MLX90640_API_stub.cpp.o

.PHONY : mlx90640/MLX90640_API_stub.o

# target to build an object file
mlx90640/MLX90640_API_stub.cpp.o:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/mlx90640/MLX90640_API_stub.cpp.o
.PHONY : mlx90640/MLX90640_API_stub.cpp.o

mlx90640/MLX90640_API_stub.i: mlx90640/MLX90640_API_stub.cpp.i

.PHONY : mlx90640/MLX90640_API_stub.i

# target to preprocess a source file
mlx90640/MLX90640_API_stub.cpp.i:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/mlx90640/MLX90640_API_stub.cpp.i
.PHONY : mlx90640/MLX90640_API_stub.cpp.i

mlx90640/MLX90640_API_stub.s: mlx90640/MLX90640_API_stub.cpp.s

.PHONY : mlx90640/MLX90640_API_stub.s

# target to generate assembly for a file
mlx90640/MLX90640_API_stub.cpp.s:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/mlx90640/MLX90640_API_stub.cpp.s
.PHONY : mlx90640/MLX90640_API_stub.cpp.s

mlx90640/MLX90640_RPI_I2C_Driver_stub.o: mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.o

.PHONY : mlx90640/MLX90640_RPI_I2C_Driver_stub.o

# target to build an object file
mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.o:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.o
.PHONY : mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.o

mlx90640/MLX90640_RPI_I2C_Driver_stub.i: mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.i

.PHONY : mlx90640/MLX90640_RPI_I2C_Driver_stub.i

# target to preprocess a source file
mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.i:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.i
.PHONY : mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.i

mlx90640/MLX90640_RPI_I2C_Driver_stub.s: mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.s

.PHONY : mlx90640/MLX90640_RPI_I2C_Driver_stub.s

# target to generate assembly for a file
mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.s:
	$(MAKE) -f CMakeFiles/mlx90640_library.dir/build.make CMakeFiles/mlx90640_library.dir/mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.s
.PHONY : mlx90640/MLX90640_RPI_I2C_Driver_stub.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mlx90640_library"
	@echo "... examples/fb.o"
	@echo "... examples/fb.i"
	@echo "... examples/fb.s"
	@echo "... examples/fbuf.o"
	@echo "... examples/fbuf.i"
	@echo "... examples/fbuf.s"
	@echo "... mlx90640/MLX90640_API_stub.o"
	@echo "... mlx90640/MLX90640_API_stub.i"
	@echo "... mlx90640/MLX90640_API_stub.s"
	@echo "... mlx90640/MLX90640_RPI_I2C_Driver_stub.o"
	@echo "... mlx90640/MLX90640_RPI_I2C_Driver_stub.i"
	@echo "... mlx90640/MLX90640_RPI_I2C_Driver_stub.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

